Repository TheTedLab/gpu-prices-bot, pull requests merged in 2023-02, with the labels that each got.

#41 Add logs for data-server #35
  src/server/data-service/src/main/java/com/gr3530904_90104/controller/RequestController.java
  src/server/data-service/src/main/java/com/gr3530904_90104/service/impl/DataServiceImpl.java
Labels: enhancement

#42 Script for adding data to database
  src/server/aggregator/data-to-database.py
Labels: enhancement

#43 Graphics fixes
  src/bot/Dockerfile
  src/bot/bot.py
  src/bot/commands.py
  src/bot/constants.py
  src/bot/requirements.txt
  src/server/aggregator/data-aggregator.py
  src/server/aggregator/data/offers-2023-01-27.json
  src/server/aggregator/data/offers-2023-01-28.json
  src/server/aggregator/data/offers-2023-01-29.json
  src/server/aggregator/data/offers-2023-01-30.json
  src/server/aggregator/data/offers-2023-01-31.json
  src/server/aggregator/data/offers-2023-02-01.json
  src/server/aggregator/data/offers-2023-02-02.json
  src/server/aggregator/data/offers-2023-02-03.json
  src/server/aggregator/data/offers-2023-02-04.json
Labels: enhancement

#46 Redo the popularity function for stores #45
  src/server/data-service/src/main/java/com/gr3530904_90104/controller/RequestController.java
  src/server/data-service/src/main/java/com/gr3530904_90104/service/DataService.java
  src/server/data-service/src/main/java/com/gr3530904_90104/service/impl/DataServiceImpl.java
Labels: invalid

#49 No data for last day for /popularity/for-shop #48
  src/server/data-service/src/main/java/com/gr3530904_90104/service/impl/DataServiceImpl.java
Labels: bug, invalid

#53 Add logs and refactoring
  docker-compose.yml
  requirements.txt
  src/bot/autorization.py.template
  src/bot/bot.py
  src/bot/commands.py
  src/bot/constants.py
  src/bot/requirements.txt
  src/bot/series_vendors.py
  src/server/aggregator/data-to-database.py
  src/server/aggregator/data/offers-2023-02-17.json
  src/server/aggregator/data/offers-2023-02-18.json
  src/server/aggregator/data/offers-2023-02-19.json
  src/server/aggregator/data/offers-2023-02-20.json
  src/server/aggregator/data/offers-2023-02-21.json
  src/server/aggregator/data/offers-2023-02-22.json
Labels: enhancement

#54 Add unit tests for java code
  src/server/data-service/.gradle/7.5.1/checksums/checksums.lock
  src/server/data-service/.gradle/7.5.1/executionHistory/executionHistory.bin
  src/server/data-service/.gradle/7.5.1/executionHistory/executionHistory.lock
  src/server/data-service/.gradle/7.5.1/fileHashes/fileHashes.bin
  src/server/data-service/.gradle/7.5.1/fileHashes/fileHashes.lock
  src/server/data-service/.gradle/7.5.1/fileHashes/resourceHashesCache.bin
  src/server/data-service/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  src/server/data-service/.gradle/buildOutputCleanup/outputFiles.bin
  src/server/data-service/.gradle/file-system.probe
  src/server/data-service/build.gradle
  src/server/data-service/src/main/java/com/gr3530904_90104/controller/RequestController.java
  src/server/data-service/src/main/java/com/gr3530904_90104/service/impl/DataServiceImpl.java
  src/server/data-service/src/main/java/com/gr3530904_90104/table/Offer.java
  src/server/data-service/src/main/java/com/gr3530904_90104/table/dto/OfferDto.java
  src/server/data-service/src/main/java/com/gr3530904_90104/table/dto/OfferDtoMapper.java
  src/server/data-service/src/test/java/com/gr3530904_90104/controller/RequestControllerTest.java
  src/server/data-service/src/test/java/com/gr3530904_90104/service/impl/DataServiceImplTest.java
  src/server/data-service/src/test/java/com/gr3530904_90104/table/dto/OfferDtoMapperTest.java
Labels: enhancement
